# fly.toml file generated for oce-stateless-firsts on 2022-07-24T23:10:14+10:00

app = "oce-stateless-firsts"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
