apiVersion: batch/v1
kind: CronJob
metadata:
  name: populate-map-list
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: populate-map-list
            image: first-tracker
            envFrom:
              - secretRef:
                  name: first-tracker
            command:
            - /bin/deno
            - run
            - -A
            - /app/util/populateMapList.ts
          restartPolicy: OnFailure
